### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by rickybloomfield** [alexandern/ccdaviewer#4]
Hi - I'm attempting to build this and am getting an error that the ccdaparser files are not found. I ran `carthage update` and it only pulled and built the SVProgressHUD framework, yet in the Xcode project it looks like both the ccdaparser.framework and the MBCircularProgressBar.framework are also required. Should there be some additional steps added to the build instructions for the viewer? Thanks!

**Comment by AlexNolasco** [comment]
> Should there be some additional steps added to the build instructions for the viewer? 

Removing the parser from the references would have fixed this, but it's best if the process is smooth.  So, I made the mini parser part of Carthage and removed the reference.  

Remove the previous version and git clone again.

**Comment by rickybloomfield** [comment]
Worked like a charm! Thanks! Looking forward to trying out the code ...
